using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SecurityLibrary
{
    public class Monoalphabetic : ICryptographicTechnique<string, string>
    {
        public string Analyse(string plainText, string cipherText)
        {
            //throw new NotImplementedException();
            plainText = plainText.ToLower();
            cipherText = cipherText.ToLower();

            Dictionary<char, char> mapDic = new Dictionary<char, char>();
            for (int i = 0; i < cipherText.Length; i++)
            {
                if (mapDic.ContainsKey(plainText[i]))
                {
                    continue;
                }
                else
                {
                    mapDic[plainText[i]] = cipherText[i];
                }

            }

            string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToLower();
            for (int i = 0; i < alphabet.Length; i++)
            {
                if (mapDic.ContainsKey(alphabet[i]) == false)
                {
                    for (int j = 0; j < alphabet.Length; j++)
                    {
                        if (mapDic.ContainsValue(alphabet[j]) == false)
                        {
                            mapDic[alphabet[i]] = alphabet[j];
                        }
                    }
                }
            }

            Dictionary<char, char> orderedDic = mapDic.OrderBy(n => n.Key).ToDictionary(n => n.Key, n => n.Value);
            string key = "";

            foreach (var c in orderedDic)
            {
                key += c.Value;
            }


            return key;

        }

        public string Decrypt(string cipherText, string key)
        {
            //throw new NotImplementedException();
            cipherText = cipherText.ToLower();
            key = key.ToLower();

            string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            string plain = "";

            for (int i = 0; i < cipherText.Length; i++)
            {
                for (int j = 0; j < key.Length; j++)
                {
                    if (cipherText[i] == key[j])
                    {
                        plain = plain + alphabet[j];
                    }
                }
            }
            return plain.ToLower();

        }

        public string Encrypt(string plainText, string key)
        {
            //throw new NotImplementedException();
            plainText = plainText.ToUpper();
            key = key.ToUpper();

            string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            string cipher = "";
            for (int i = 0; i < plainText.Length; i++)
            {
                for (int j = 0; j < key.Length; j++)
                {
                    if (plainText[i] == alphabet[j])
                    {
                        cipher = cipher + key[j];
                    }
                }
            }
            return cipher;
        }







        /// <summary>
        /// Frequency Information:
        /// E   12.51%
        /// T	9.25
        /// A	=
        /// O	7.60
        /// I	7.26
        /// N	7.09
        /// S	6.54
        /// R	6.12
        /// H	5.49
        /// L	4.14
        /// D	3.99
        /// C	3.06
        /// U	2.71
        /// M	2.53
        /// F	2.30
        /// P	2.00
        /// G	1.96
        /// W	1.92
        /// Y	1.73
        /// B	1.54
        /// V	0.99
        /// K	0.67
        /// X	0.19
        /// J	0.16
        /// Q	0.11
        /// Z	0.09
        /// </summary>
        /// <param name="cipher"></param>
        /// <returns>Plain text</returns>
        /// 

        public string AnalyseUsingCharFrequency(string cipher)
        {
            string largePlain = "JULYPREVIOUSMONTHNEXTMONTHMEMBERSUPDATEFIRSTSCREENEDITORIALBACKONMYSOAPBOXWHYISITTHATUSEOFTHEENGLISHLANGUAGEISGETTINGSOVERYSLOPPYHOWLONGAGOWASITWHENGRAMMARCEASEDTOBEANESSENTIALELEMENTOFWRITINGADECENTESSAYAWHILEAGOTHEREWASACAMPAIGNTODOAWAYWITHTHEABERRANTAPOSTROPHENOWITSEEMSWENEEDANEWCAMPAIGNTOCONTENDWITHTHEABERRANTHYPHENYESIKNOWTHEREISAVASTDIFFERENCEBETWEENABLACKCABDRIVERANDABLACKCABDRIVERBUTNONEOFMYREFERENCEBOOKSINVITESHYPHENATIONOFBLACKCABORDRIVERANEXTREMEEXAMPLEPERHAPSBUTIMGETTINGTIREDOFSORTINGOUTHYPHENATEDWORDSANDREPLACINGTHEHYPHENWITHACOMMAORSEMICOLONORCREATINGANEWSENTENCENOOFCOURSEIMNOTPERFECTNOONEISBUTINOTONLYABHORTHEINAPPROPRIATEUSEOFAHYPHENIALSORECOGNISEASPLITINFINITIVEWHENISEEONEITMAYBEACCEPTABLEFORTHESTARSHIPENTERPRISETOBOLDLYGOBUTIDONOTTHINKTHATLOCALORGANISATIONSSHOULDBEENCOURAGEDTOPROACTIVELYENGAGEDEPARTMENTOFWORKANDPENSIONSPRESSRELEASEIRELYONJULIETOCHECKTHEPROOFCOPYOFUPDATEBEFOREYOUSEEITANDSHEWONTLETCARELESSUSEOFGRAMMARSLIPTHROUGHOOPSISHOULDNOWSAYIUSEDTORELYONJULIEASIWROTETHATBEFORESHEHANDEDINHERNOTICENOBEFOREYOUASKIDONTTHINKITWASANYTHINGISAIDORDIDSPECIFICALLYASMANYREADERSWILLKNOWADSETPROVIDEDOFFICESPACEFORTHEADMINISTRATIONFUNCTIONSOFNAEGAWITHJULIEWORKINGFORNAEGAFORTWELVEHOURSAWEEKINTHATSPACETHATCONTRACTCAMETOANABRUPTENDINMAYANDICANNOTFINDWORKWITHINTHEADSETSETUPTOMAKEUPTHOSEMISSINGHOURSSORATHERTHANTRYTOFINDASECONDPARTTIMEJOBJULIEHASFOUNDHERSELFFULLTIMEWORKSHEWILLBEGREATLYMISSEDNOTLEASTFORHERABILITYTOSPOTANABERRANTHYPHENORAPOSTROPHECHANGESAREAFOOTWELLTHEYWOULDHAVETOBEWOULDNTTHEYDAWNYESTHEONEWHOWRITESTHEFUNNYCOMMENTSINUPDATEWILLBETAKINGOVERJULIESJOBOFTHENEWSPAPERSTHETIMINGISRIGHTASHERYOUNGESTSTARTSFULLTIMESCHOOLINSEPTEMBERRUTHWARNERWHOMMANYOFYOUALREADYKNOWASADSETSDATAMANAGERALSOINCONTROLOFTHEWEBSITEWILLBETAKINGOVERASMEMBERSHIPSECRETARYASFORHELPINTHEOFFICEIMINTERVIEWINGFOURPEOPLETOMORROWANDEXPECTTOBEABLETOAPPOINTONEOFTHEMTOSTARTONAUGUSTTHATGIVESHERTHEYAREALLFEMALETHREEWEEKSTOFINDHERFEETBEFOREIGOONHOLIDAYFORAWEEKINEVERTHOUGHTTHATIDBEBLESSINGMOBILEPHONESBUTITHINKTHATITMIGHTBENEEDEDANDTHEFAMILYWILLFORONCEHAVETOACCEPTITTHEWIDERWORLDTHELSCHASBEENTAKINGABITOFAHAMMERINGTHISMONTHWITHTHEASSOCIATIONOFCOLLEGESSTILLASSERTINGTHATTHEREARECLEARTENSIONSBETWEENTHECENTREANDTHEARMSANDINSTITUTEOFDIRECTORSSAYINGTHATTHEORGANISATIONHASMADELITTLEIFANYIMPACTONBUSINESSTHEFUNDINGOFLEARNINGANDTHEPEOPLEWHOUNDERTAKEITCONTINUESTODOMINATETHEEDUCATIONALPRESSWHILSTTHEPROVISIONOFADDITIONALMONEYUNDERTHECOMPREHENSIVESPENDINGREVIEWISWELCOMEDITSNOTENOUGHISITEVERITSEEMSTHETHEPOWERSTHATBEAREWAKINGUPTOTHEIDEATHATMAYBEJUSTMAYBEAIMINGFORAPAPERLESSSOCIETYWASNOTSUCHAGOODIDEAATLEASTNOTUNTILYOUCANBECERTAINOFBEINGABLETORETRIEVETHEINFORMATIONCREATEDWELCOMETONEWMEMBERSCAMBRIDGESHIREGRIDFORLEARNINGCONTACTLILYDAINTERTELLOGWOODMANAGEMENTCONSULTANTSLTDCONTACTVELMABENNETTTELDETAILSOFTHEWORKOFTHESETWOORGANISATIONSWILLBEPLACEDONTHEADSETWEBSITEJUSTASSOONASWEGETTHEMTOTOPOFPAGETOINDEXCIPDURGESCAUTIONONEMPLOYEERIGHTSREVIEWPATRICIAHEWITTSECRETARYOFSTATEFORTRADEANDINDUSTRYHASTODAYJULYLAUNCHEDAREVIEWOFTHEEMPLOYMENTRELATIONSACTTHEREVIEWWILLLOOKATCOMPULSORYTRADEUNIONRECOGNITIONMEASURESALTHOUGHCHANGESWILLBELIMITEDACCORDINGTOTHEDTITHECIPDEXPRESSESCAUTIONABOUTTHEINITIATIVEDIANESINCLAIRLEADPUBLICPOLICYADVISERRESPONDEDTHELAWISWORKINGWELLATTHEMOMENTANDISFINELYBALANCEDBETWEENEMPLOYERSANDEMPLOYEESFORINSTANCEMANYTRADEUNIONSARECURRENTLYWINNINGCLAIMSUNDERTHEACTWEHOPETHATTHEGOVERNMENTALLOWSTHISLEGISLATIONTOBEDDOWNBEFORECHANGESARECONSIDEREDTHEDTIHASALSOLAUNCHEDACONSULTATIONDOCUMENTTODAYONIMPLEMENTINGTHEEUDIRECTIVEONINFORMINGANDCONSULTINGSTAFFINTHEUKTHISISDUETOCOMEINTOEFFECTINTHEUKFORORGANISATIONSOFMORETHANSTAFFBYMARCHANDFORSMALLERORGANISATIONSBYMARCHORGANISATIONSEMPLOYINGLESSTHANPEOPLEARELIKELYTOBEEXCLUDEDCIPDPRESSRELEASEJULYTOTOPOFPAGETOINDEXJOHNSONHERALDSNEWERAFORBRITISHFIRMSNEWPROPOSALSTOCUTREDTAPEANDSAVESMALLBUSINESSESAROUNDMILLIONAYEARWEREUNVEILEDTODAYJULYWITHTHEPUBLICATIONOFTHEGOVERNMENTWHITEPAPERMODERNISINGCOMPANYLAWTHEWHITEPAPERREFLECTSTHECHANGESINTHEBUSINESSENVIRONMENTINRECENTYEARSPARTICULARLYTHEGROWTHOFSMALLBUSINESSESANDADVANCESINCOMMUNICATIONSTECHNOLOGYANDINCLUDESPLANSTOSIMPLIFYTHELAWANDREDUCEBURDENSONSMALLFIRMSIMPROVETRANSPARENCYTOINCREASECONFIDENCEINBUSINESSANDIMPROVEGOVERNANCETOENCOURAGEANDSUPPORTRESPONSIBLEBUSINESSOTHERKEYPROPOSALSINCLUDEDIRECTORSDUTIESWILLBESETOUTCLEARLYINSTATUTEFORTHEFIRSTTIMECORPORATEDIRECTORSWILLBEPROHIBITEDPRIVATECOMPANIESNOLONGERWILLHAVETOAPPOINTCOMPANYSECRETARIESPRIVATECOMPANIESNOLONGERWILLHAVETOHOLDAGMSUNLESSMEMBERSWANTTHEMCOMPANIESWILLBEABLETOEXPLOITTHEINTERNETANDEMAILTOMAKEDECISIONSCOMPANIESWILLHAVESIMPLERREPORTSANDACCOUNTSACCOUNTSWILLBEFILEDMOREQUICKLYWITHINSEVENMONTHSFORPRIVATECOMPANIESANDSIXMONTHSFORPUBLICCOMPANIESQUOTEDCOMPANIESWILLHAVETOPOSTREPORTSONWEBSITESBEFORETHISTHELARGESTCOMPANIESWILLPUBLISHANOPERATINGANDFINANCIALREVIEWCOMPANIESANDTHEIRDIRECTORSCONVICTEDOFFLOUTINGCOMPANYLAWCOULDBENAMEDINACENTRALREGISTERTHEWHITEPAPERISAVAILABLEONLINEATWWWDTIGOVUKCOMPANIESBILLASUMMARYOFTHEMEASURESOFPARTICULARINTERESTTOSMALLBUSINESSISALSOAVAILABLEDTIPRESSRELEASEPJULYTOTOPOFPAGETOINDEXCBIPRAISESCOMPANYLAWREFORMPLANSTHECONFEDERATIONOFBRITISHINDUSTRYCBIISBACKINGGOVERNMENTPROPOSALSTOREFORMCOMPANYLAWITISHOPEDTHATTHISWILLSIMPLIFYTHEREGIMEFORSMALLFIRMSWHILEIMPROVINGACCOUNTABILITYFORLARGEROGANISATIONSTHECBIISPRAISINGGOVERNMENTPLANSTOIMPLEMENTTHERECOMMENDATIONSOFTHECOMPANYLAWREVIEWITISHOPEDTHATTHISWILLMAKETHELAWCLEARERANDMOREEFFECTIVEHRLOOKJULYTOTOPOFPAGETOINDEXPATRICIAHEWITTANNOUNCESNEWAPPOINTMENTSTOTHESMALLBUSINESSCOUNCILSECRETARYOFSTATEFORTRADEANDINDUSTRYPATRICIAHEWITTTODAYJULYANNOUNCEDTHEFULLNEWMEMBERSHIPOFTHESMALLBUSINESSCOUNCILSBCTHEMEMBERSWORKWITHTHECHAIRMANWILLIAMSARGENTTOADVISETHEGOVERNMENTONISSUESAFFECTINGSMALLBUSINESSESTHESBCREPRESENTSAWIDERANGEOFSECTORSINCLUDINGMANUFACTURINGRETAILSOCIALENTERPRISETOURISMBUSINESSSUPPORTENVIRONMENTALBUSINESSESMEDIAANDENTERTAINMENTRECRUITMENTACCOUNTANCYANDACADEMIATHEMEMBERSHIPREPRESENTSALLPARTSOFTHEUKANDINCLUDESPEOPLEOFDIFFERENTAGESANDBACKGROUNDSDTIPRESSRELEASEPJULYUPDATECOMMENTTHEPRESSRELEASELISTSTHEPEOPLEWITHSHORTBIOGSANDSOMEOFTHEMREALLYAREFROMSMALLBUSINESSESTOTOPOFPAGETOINDEXSMALLBUSINESSSECTORGROWTHEQUIVALENTTOOVERNEWSTARTUPSEVERYDAYNIGELGRIFFITHSHAILSNETINCREASEINBUSINESSPOPULATIONNEWFIGURESPUBLISHEDTODAYJULYSHOWTHEREWASANETINCREASEOFMORETHANFIRMSOPERATINGINTHEUKINCOMPAREDTOTHEPREVIOUSYEAREQUIVALENTTOOVERNEWBUSINESSESSTARTINGUPEVERYDAYACCORDINGTONEWSTATISTICSFROMTHEDTISSMALLBUSINESSSERVICESBSTHEBUSINESSPOPULATIONTOTALLEDLASTYEARCOMPAREDTOINTHEYEAROTHERFINDINGSSHOWTHEREWEREMILLIONMOREBUSINESSESTHANINTHEFIRSTYEARFORWHICHCOMPARABLEFIGURESAREAVAILABLETHENUMBEROFMEDIUMSIZEDBUSINESSESREACHEDFORTHEFIRSTTIMEINSEVENYEARSANDATLEASTOFBUSINESSESINALLINDUSTRIESWERESMESTHEFULLSTATISTICSCANBEDOWNLOADEDFROMTHESMALLBUSINESSSERVICEWEBSITEATWWWSBSGOVUKSTATISTICSDTIPRESSRELEASEPJULYTHEGAMECOMESTIMATESTHATWORLDCUPABSENTEEISMCOSTTHEUKAROUNDMILLIONTHISFIGUREISONLYATENTHOFTHEPREDICTEDCOSTSINCEMANYEMPLOYERSWERECOOPERATIVEANDALLOWEDEMPLOYEESTOEITHERCHANGETHEIRHOURSORWATCHTHEMATCHESATWORKHOWEVEROFFANSSTILLADMITTEDTOTAKINGATLEASTONEDAYASSICKLEAVEIRSEMPLOYMENTREVIEWISSUEJULYTOTOPOFPAGETOINDEXCOMMUNICATIONSKILLSLACKINGATTHETOPACCORDINGTONEWRESEARCHFROMTHEAZIZCORPORATIONBRITAINSTOPBUSINESSLEADERSARELARGELYUNHEARDUNRECOGNISEDANDCONSIDEREDUNABLETOCOMMUNICATEEFFECTIVELYBYTHEIRBUSINESSPEERSTHERESEARCHREVEALEDTHATWHILEOFUKCOMPANYDIRECTORSCONSIDERUSBUSINESSEXECUTIVESTOHAVEANEXCELLENTORGOODMEDIAIMAGEANDREPUTATIONONLYBELIEVETHESAMEOFUKEXECUTIVESINADDITIONFEELTHATTHEMEDIAIMAGEOFTHEUKSLEADINGBUSINESSEXECUTIVESISINNEEDOFIMPROVEMENTTRAININGZONELEARNINGWIREISSUEJULYTOTOPOFPAGETOINDEXTHEHUMBLELEADERANARTICLEINBULLETPOINTJUNEISSUEARGUESTHATHAVINGALARGERTHANLIFECORPORATEHEROASALEADERCANBEDETRIMENTALTOANORGANISATIONTHEMAINCRITICISMSOFTHISTYPEOFLEADERARETHATTHEYARESELFSERVINGMOREINTERESTEDINSELFPROMOTIONANDCELEBRITYTHANTEAMWORKTHEARTICLEFURTHERSUGGESTSTHATINMANYCASESTHEYFAILTOADDVALUEDONOTDELIVERSUSTAINABLERESULTSANDDONTWORKTOIMPROVEPERFORMANCETHEARTICLETELLSUSTHATTRULYTRANSFORMATIONALLEADERSHAVEANEQUALRATIOOFHUMILITYANDPROFESSIONALWILLTHEYAREABLEMANAGERSRATHERTHANAFGUREHEADFORTHEMEDIAANDCANENGENDEREMPLOYEETRUSTCOMMITMENTANDLOYALTYTHEYWILLALSOHAVEADESIRETOSHUNPUBLICITYCHANNELAMBTIONINTODEVELOPINGTHECOMPANYNOTTHEMSELVESGIVECREDITTOOTHERSAROUNDTHEMANDDESPISEMEDIOCRITYTOTOPOFPAGETOINDEXWHATAMESSPARTICPATIONASASMPLEMANAGERIALRULETOCOMPLEXIFYORGANISATIONSACTUALLYASERIOUSRESEARCHPAPERWHICHLOOKSATSOMEOFTHESIMPLERULESOFMANAGEMENTWHCHNTHEENDCANFOULUPOURLIVESFORGOODBUTONLYIFWELETTHEMWEALLIASSUMEKNOWOFTHEHORSEMADEBYACOMMITTEEINTODAYSCONSULTATIVECLMATEWECOULDBEHEADINGFORTRYINGTODEALINCAMELSUNLESSULTIMATELYTHEMANAGERIETHESINGLEPERSONRESPONSIBLEFORMAKINGANDIMPLEMENTNGTHEDECISIONDECIDESOURHORSESSHOULDNOTHAVEHUMPSWHETHERONEORTWOISIMMATERIALSOINTHEENDWEHAVETHEAUTOCRATICDICTATORIALVICTORIANPARENTWHOSEOFFSPRINGMIGHTIFDARINGTOQUESTIONRECEIVETHERESPONSEBECAUSEISAYITISJOURNALOFMANAGEMENTSTUDIESMARCHUPDATECOMMENTONTHEOTHERHANDTHEEUROPEANDIRECTIVESAYSTHOUSHALTCONSULTANDATLENGTHUNLESSTHEREARELESSTHANSTAFFINYOURORGANISATIONSORRYGUYSTHATMEANSTHATICANCONTINUETOBETHEAUTOCRATCDCTATORIALPARENTTYPEATLEASTINLAWIFNOTREALITYTOTOPOFPAGETOINDEXLEADERSNEEDMORETRAININGAYEARAFTERTHELIBRARYWORLDSRECRUTRETANANDLEADREPORTWARNEDOFFALLINGSTANDARDSINEXECUTIVEABILITYMUSEUMSAREFACINGASIMLARLEADERSHIPCRISISSPEAKINGATTHEANNUALMUSEUMDRECTORSCONFERENCELIZAMOSOFTHECOUNCILFOREXCELLENCEINMANAGEMENTANDLEADERSHIPTOLDDELEGATESTHATTHEYSHOULDHEEDTHEDSQUETBEINGVOICEDBYJUNIORANDMIDDLEMANAGERSINTHEPUBLICSECTORACCORDNGTOARECENTREPORTOFJUNIORANDMIDDLEMANAGERSCLAIMTHATLEADERSHPNTHEIRORGANISATIONISPOORMSAMOSBELIEVESTHATTHISMATTERSBECAUSEGOODLEADERSCANNSPIREANDENERGISETHEIREMPLOYEESWHICHHASAPOSTVEEFFECTONPERFORMANCELIBRARYANDINFORMATIONUPDATEJULYVOLTOTOPOFPAGETOINDEXPATHTOTHEGATEWAYISCLEAREDAYEARAGOANENTREPRENEURSEEKINGHELPTOSETUPACOMPANYINGLASGOWRISKEDBEINGKNOCKEDDOWNINARUSHOFAGENCIESBRANDISHINGMORETHANDIFFERENTSUPPORTPRODUCTSANDSERVICESNEWBUSINESSESFACEDABEWILDERINGCHOICEOFDIFFERENTPUBLICSECTORAGENCIESPROVIDINGACCESSTOOVERBUSINESSSUPPORTPARTNERSHPSMOSTLYKNOWNBYCONFUSINGTHREELETTERACRONYMSYETDESPITETHEWELTEROFSERVICESAVAILABLEWITHLITERALLYHUNDREDSOFADVISERSGRANTSANDTRAININGSCHEMESONOFFERRESEARCHSHOWEDTHATGLASGOWURGENTLYNEEDEDTOFINDBETTERWAYSTOIMPROVEITSBUSINESSBIRTHRATEANDITSINDIGENOUSCOMPANYSURVIVALRATETHEVULNERABILITYOFSMALLANDMEDIUMSIZEDENTERPRISESSMESTOFAILURENTHEIREARLYYEARSISCLEARANDINGLASGOWONLYOFSMESSURVIVELONGERTHANTHREEYEARSCOMPAREDTOTHENATIONALTHREEYEARSURVIVALRATEOFONTOPOFLOWERTHANAVERAGESURVIVALRATESGLASGOWALSOHADAPROBLEMWITHEUROPEANBUSINESSGRANTSBEINGLEFTUNCLAIMEDBECAUSEELIGIBLECOMPANESDDNOTAPPLYFORTHECASHONOFFERDUNCANTANNAHILLCHIEFEXECUTIVEOFGLASGOWCHAMBEROFCOMMERCESEZEDTHECHANCETOPOOLTHERESOURCESOFTHEPRIVATEANDPUBLCSECTORSINAMAJOREFFORTTOADDRESSTHESHORTCOMINGSOFTHESYSTEMANDCREATEASNGLEPOINTOFENTRYFORCOMPANIESSEEKNGHELPATANYSTAGEOFTHEIRDEVELOPMENTSMALLBUSINESSGATEWAYISATVALERIEDARROCHSCOTTISHHERALDJULYMYSCHOOLDAYSWERETHEHAPPESTDAYSOFMY".ToLower();

            Dictionary<char, int> orderedbyfrequancyC = GetFrequency(ref cipher);
            Dictionary<char, int> orderedbyfrequancyP = GetFrequency(ref largePlain);

            char[] freqText = orderedbyfrequancyC.Keys.ToArray();
            char[] freqPlain = orderedbyfrequancyP.Keys.ToArray();
            string plainText = "";

            for (int i = 0; i < cipher.Length; i++)
            {
                for (int j = 0; j < freqText.Length; j++)
                {
                    if (cipher[i] == freqText[j])
                    {
                        plainText = plainText + freqPlain[j];
                    }
                }
            }
            return plainText;

        }
        static Dictionary<char, int> GetFrequency(ref string input)
        {
            Dictionary<char, int> freq = new Dictionary<char, int>();

            for (int i = 0; i < input.Length; i++)
            {
                if (freq.ContainsKey(input[i]))
                {
                    freq[input[i]] = freq[input[i]] + 1;
                }
                else
                {
                    freq[input[i]] = 1;
                }
            }
            return freq.OrderByDescending(n => n.Value).ToDictionary(n => n.Key, n => n.Value);

        }

    }
}